name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cudatoolkit=11.8.0
  - plyfile
  - python=3.8
  - pip
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
